### ISSUE TITLE
Specify/change how vals are handled?

### ISSUE THREAD

**Issue by oleg-py** [Thangiee/Freasy-Monad#2]
First, thanks for nice little library, really cuts in boilerplate and Intellij support is cool.

There's one thing that was not completely obvious, and that is how `val`s inside trait will be treated. Turns out, they are simply removed. I think this behavior deserves to at least be mentioned in README.

Alternatively, what might be done is treating vals like defs, so that abstract val gets converted to an object extending sealed trait, and non-abstract vals are retained as they are.

Also, it might make sense to do something specific with `var`s too, maybe prohibit abstract altogether and retain non-abstract?

```scala
import cats.free.Free
import freasymonad.free

@free trait Data {
  type Store[A] = Free[StoreADT, A]
  sealed trait StoreADT[A]

  val value: String = "This value will be evicted"

  def read[A]: A

}

object Run extends App {
  println(Data.ops.value) // does not compile
}
```

**Comment by Thangiee** [comment]
Thanks for the feedback. :)

So based on your example and suggestions, what are your thoughts on changing it to something like this:

* concrete def/val with **Store[A]** return type -> include in `ops`
* concrete def/val/var with other return type -> retain as is
    -  also, should it be moved outside of `ops`? e.g. `Data.ops.value` to `Data.value`
* abstract def/val with **Store[A]** return type -> case class/obj extending sealed trait
* abstract def/val/var with other return type -> prohibit with compile error

**Comment by oleg-py** [comment]
Something like this, yes. And maybe specify that abstract var with **Store[A]** is a compile error too.

Maybe avoid moving stuff outside of `ops` - changing function location based on its return type is a strange behavior, I'd say.

**Comment by Thangiee** [comment]
I just finished implementing those features. Could you test it out to see if everything looks good. Thx.
 
```scala
resolvers += "Artifactory" at "https://oss.jfrog.org/artifactory/oss-snapshot-local/"
libraryDependencies ++= Seq(
  "com.thangiee" %% "freasy-monad" % "0.3.0-SNAPSHOT",
  "org.typelevel" %% "cats" % "0.7.2"
)
addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.0" cross CrossVersion.full)
```
Intellij plugin: https://github.com/Thangiee/Freasy-Monad/blob/dev/plugin/bin/freasy-monad-plugin-0.3.0.zip

**Comment by oleg-py** [comment]
Seems to work just right 👍
