### ISSUE TITLE
Freasy Monad Plugin Kills IntelliJ

### ISSUE THREAD

**Issue by prahim** [Thangiee/Freasy-Monad#5]
I used the freasy-monad-plugin-assembly-0.4.0.jar plugin with intelliJ (running on Ubuntu) and it causes the following error: 

`NoSuchMethodError: org.jetbrains.plugins.scala.lang.psi.api.statements.params.ScParameters.text()Ljava/lang/String;`

After a while, the IDE either freezes up and I have to reboot or my clipboard stops working until I remove the plugin.

I would appreciate it if this issue were resolved asap.

Thank you!

**Comment by Thangiee** [comment]
Hi, 

Can you tell me which intellij and JDK version you're using?

Thanks

**Comment by prahim** [comment]
I am using:

IntelliJ IDEA 2016.1.4
Build #IC-145.2070, built on August 2, 2016
JRE: 1.8.0_76-release-b198 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by Thangiee** [comment]
Sorry for the delays. Turned out the plugin was using some methods that were not in older versions of Intellij. It should be fixed now. 

Please reopen if the issue persist. Thanks!
