### ISSUE TITLE
Idea plugin thinks there are ADT members for non-abstract methods.

### ISSUE THREAD

**Issue by Baccata** [Thangiee/Freasy-Monad#7]
In the case of `KVStore`,  the Get and Put case classes are generated by the `@free` annotation, however, IntelliJ sees members `Get`,  `Put` and `Update` in the GrammarADT when providing auto-completion.

**Comment by Thangiee** [comment]
Could you try taking a screen shot of that behavior?

Thanks

**Comment by Baccata** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/4439335/20169105/99417be8-a71d-11e6-9b4b-10cbcbecd729.png)

I'm running version 0.5.0 of the freasy plugin, on intellij idea ultimate 2016.2.5 with scala plugin version 2016.2.1.
