### ISSUE TITLE
Issue compiling when context bounds are used

### ISSUE THREAD

**Issue by kthompson** [Thangiee/Freasy-Monad#9]
Here is an example of a bit of code we are having some trouble getting to work.

```
import cats.free._
import spray.json._
import freasymonad.cats.free

@free
trait DataStore {
  type DataStoreF[A] = Free[DataStoreGrammar, A]
  sealed trait DataStoreGrammar[A]
  
  def getAll[T: JsonReader](): List[T]
}
```

At the moment we are working around the issue by using:
`  def getAll[T: JsonReader](unit: Unit): List[T]`

**Comment by Thangiee** [comment]
Should be fixed in version 0.6.0
https://github.com/Thangiee/Freasy-Monad/blob/master/jvm/src/test/scala/compilation/Issue9.scala

**Comment by kthompson** [comment]
I tried this this morning and context bounds in general do not appear to work. 

If I declare a method like:

```def create[T](value: T)(implicit writer: JsonWriter[T]): DataStoreF[String]```

It works but 

```def create[T: JsonWriter](value: T): DataStoreF[String]```

does not and results in some errors stating the JsonWriter cannot be found.

**Comment by Thangiee** [comment]
Did you get a compiler error or is it an IntelliJ highlighting error?

**Comment by kthompson** [comment]
It was a compiler error. I have uninstalled the old plugin.
